# Generated by Django 6.0.7 on 2026-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='opens_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
