# Generated by Django 6.0.6 on 2026-07-29 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0003_attentioncheck_focusevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardErase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_index', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('stroke_ids', models.JSONField(default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_erases', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_erases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_grants', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='unique_lesson_board_grant')],
            },
        ),
        migrations.CreateModel(
            name='BoardSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('strokes', models.JSONField(default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_sheets', to='lessons.lesson')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'index'), name='unique_lesson_sheet_index')],
            },
        ),
    ]
