# Generated by Django 6.0.6 on 2026-07-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='homework/tasks/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
