# Generated by Django 6.0.7 on 2026-08-12 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_assignment_attachment_assignment_attachment_name_and_more'),
        ('lessons', '0008_lessonrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lessons.lesson'),
        ),
    ]
