# Generated by Django 6.0.7 on 2026-08-12 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_assignment_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_grade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('checking', 'Tekshirilmoqda'), ('pending_review', "O'qituvchi ko'rib chiqishi kutilmoqda"), ('done', 'Tasdiqlangan'), ('error', 'Xatolik')], db_index=True, default='checking', max_length=15),
        ),
        migrations.CreateModel(
            name='AssignmentFocusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('exit', 'Sahifadan chiqdi'), ('return', 'Sahifaga qaytdi')], max_length=8)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_events', to='homework.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_focus_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
