# Generated by Django 6.0.8 on 2026-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_submission_ai_grade_submission_ai_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='reminder_1h_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reminder_halfway_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
