# Generated by Django 6.0.7 on 2026-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_assignment_reminder_1h_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_language',
            field=models.CharField(default='uz', max_length=8),
        ),
    ]
