# Generated by Django 6.0.6 on 2026-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('declined', 'Rad etilgan')], db_index=True, default='approved', max_length=10),
        ),
    ]
