# Generated by Django 6.0.6 on 2026-08-04 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_attentioncheck_focusevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('egress_id', models.CharField(blank=True, max_length=64)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('recording', 'Yozilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='recording', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
