# Generated by Django 6.0.6 on 2026-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_focusalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecording',
            name='status',
            field=models.CharField(choices=[('pending', 'Boshlanmoqda'), ('recording', 'Yozilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10),
        ),
    ]
