# Generated by Django 6.0.7 on 2026-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_micrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecording',
            name='audio_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='audio_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='audio_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='video_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='video_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrecording',
            name='video_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonrecording',
            name='status',
            field=models.CharField(choices=[('pending', 'Boshlanmoqda'), ('recording', 'Yozilmoqda'), ('merging', 'Birlashtirilmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=10),
        ),
    ]
