# Generated by Django 6.0.7 on 2026-09-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lessonrecording_audio_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
