# Generated by Django 6.0.8 on 2026-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
