# Generated by Django 6.0.7 on 2026-09-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('system', 'Tizim')], default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='system_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='system_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
